---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 3389, host: 3389}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: opentable/win-2012r2-standard-amd64-nocm
    transport:
      name: winrm
      elevated: true
      elevated_username: System
      elevated_password: null

suites:
  - name: default
    run_list:
      - recipe[base_windows_remedation::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
